### ISSUE TITLE
SS+ (or SSH) displayed as X.

### ISSUE THREAD

**Issue by blinchk** [OctoDumb/osubot#4]
![image](https://user-images.githubusercontent.com/49353043/104135200-a2226280-539f-11eb-9110-73d793bbceeb.png)

**SS+ grade displayed as X in bot's response.**

**Comment by blinchk** [comment]
Also after visiting osu!track I noticed, that this issue isn't only at osu!bot.
![image](https://user-images.githubusercontent.com/49353043/104135268-40162d00-53a0-11eb-832b-a40388154611.png)

**Comment by blinchk** [comment]
After some research I found a conclusion, that this problem at osu!web. 
I will open new issue at there.

**Comment by blinchk** [comment]
[Issue at osu!api repository](https://github.com/ppy/osu-api/issues/313)

**Comment by uzervlad** [comment]
Reopening this issue, as there's still inconsistency in ranks between different servers, which should be fixed in the future.

![1610313391481.jpg](https://user-images.githubusercontent.com/24654479/104135575-558c5680-53a2-11eb-92b9-0cc4401bfdd1.jpg)

**Comment by blinchk** [comment]
> Reopening this issue, as there's still inconsistency in ranks between different servers, which should be fixed in the future.

Судя по issues в репозиториях ppy (osu!api) это связано напрямую с Bancho.
Если issue там получит ответ не за 300 лет, то вполне возможно, что проблема будет уже решена.

**Comment by uzervlad** [comment]
На гатари SS тоже выводится как X.
Плюс, подобные изменения в апи могут сломать многих ботов. Лучше просто поменять вывод в самом боте.

**Comment by blinchk** [comment]
> На гатари SS тоже выводится как X.
> Плюс, подобные изменения в апи могут сломать многих ботов. Лучше просто поменять вывод в самом боте.

https://github.com/ppy/osu-api/issues/313#issuecomment-757546978
Дали ответ, что это нормально, и так должно быть на Bancho.
